# 1. Import SignLanguageModule notebook

In [1]:
import import_ipynb
import SignLanguageModule as signLangModule # notebook converted as .py file

ERROR: Invalid requirement: '#'


['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


# 2. Collect Keypoint Values for Training and Testing

In [2]:
# Call function to collect keypoints from SignLanguageModule
# signLangModule.collect_keypoints()

# 3. Preprocess Data and Create Labels and Features

In [2]:
# Import dependencies
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [3]:
import os
import numpy as np

In [4]:
# Create label map for the signs defined in SignLanguageModule
# to be used when creating training data in testing data
label_map = {label:num for num, label in enumerate(signLangModule.signs)}

In [5]:
label_map

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25,
 'hello': 26,
 'my': 27,
 'name': 28,
 'is': 29,
 'nice': 30,
 'you': 31,
 'bye': 32,
 'thank you': 33,
 'to meet': 34}

In [6]:
# Sequences for feature (x) data
# Labels for representing labels (y) data
sequences, labels = [], []
for sign in signLangModule.signs:
    for sequence in np.array(os.listdir(os.path.join(signLangModule.DATA_PATH, sign))).astype(int):
        window = []
        for frame_num in range(signLangModule.sequence_length):
            res = np.load(os.path.join(signLangModule.DATA_PATH, sign, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[sign])

In [6]:
np.array(sequences).shape #check this one for all signs

(2100, 30, 1662)

In [7]:
np.array(labels).shape #check this too

(2100,)

In [7]:
# Store sequences into numpy array to work with
X = np.array(sequences)

# Convert initial labels, encode them as one-code representation/binary flat
y = to_categorical(labels).astype(int)

# Specify test data proportion (20% of the data)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y) 

In [8]:
y_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [9]:
X_train.shape

(1680, 30, 1662)

In [8]:
# Instantiate model
model = signLangModule.createModel()

In [9]:
# Check model summary
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 30, 64)            442112    
_________________________________________________________________
lstm_1 (LSTM)                (None, 30, 128)           98816     
_________________________________________________________________
lstm_2 (LSTM)                (None, 64)                49408     
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense (Dense)                (None, 700)               45500     
_________________________________________________________________
dropout_1 (Dropout)          (None, 700)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 700)               4

In [13]:
signLangModule.signs.shape[0]

35

# 4. Train the LSTM Neural Network

In [10]:
# Train the built LSTM neural network 
model.fit(X_train, y_train, batch_size=128, epochs=1000, callbacks=[signLangModule.tb_callback])

Epoch 1/1000
14/14 [==============================] - 5s 143ms/step - loss: 3.7568 - categorical_accuracy: 0.0256
Epoch 2/1000
14/14 [==============================] - 2s 121ms/step - loss: 3.5509 - categorical_accuracy: 0.0256
Epoch 3/1000
14/14 [==============================] - 2s 122ms/step - loss: 3.5145 - categorical_accuracy: 0.0238
Epoch 4/1000
14/14 [==============================] - 2s 124ms/step - loss: 3.5596 - categorical_accuracy: 0.0298
Epoch 5/1000
14/14 [==============================] - 2s 126ms/step - loss: 3.5387 - categorical_accuracy: 0.0310
Epoch 6/1000
14/14 [==============================] - 2s 129ms/step - loss: 3.6398 - categorical_accuracy: 0.0298
Epoch 7/1000
14/14 [==============================] - 2s 130ms/step - loss: 3.5594 - categorical_accuracy: 0.0262
Epoch 8/1000
14/14 [==============================] - 2s 132ms/step - loss: 3.5555 - categorical_accuracy: 0.0321
Epoch 9/1000
14/14 [==============================] - 2s 133ms/step - loss: 3.5616 - cat

14/14 [==============================] - 2s 159ms/step - loss: 3.5615 - categorical_accuracy: 0.0298
Epoch 73/1000
14/14 [==============================] - 3s 179ms/step - loss: 3.5559 - categorical_accuracy: 0.0292
Epoch 74/1000
14/14 [==============================] - 2s 174ms/step - loss: 3.5553 - categorical_accuracy: 0.0321
Epoch 75/1000
14/14 [==============================] - 3s 180ms/step - loss: 3.5566 - categorical_accuracy: 0.0321
Epoch 76/1000
14/14 [==============================] - 3s 179ms/step - loss: 3.5554 - categorical_accuracy: 0.0220
Epoch 77/1000
14/14 [==============================] - 2s 174ms/step - loss: 3.5552 - categorical_accuracy: 0.0292
Epoch 78/1000
14/14 [==============================] - 2s 163ms/step - loss: 3.5551 - categorical_accuracy: 0.0274
Epoch 79/1000
14/14 [==============================] - 2s 165ms/step - loss: 3.5510 - categorical_accuracy: 0.0387
Epoch 80/1000
14/14 [==============================] - 3s 184ms/step - loss: 3.5374 - categori

14/14 [==============================] - 2s 150ms/step - loss: 3.5543 - categorical_accuracy: 0.0280
Epoch 143/1000
14/14 [==============================] - 2s 150ms/step - loss: 3.5490 - categorical_accuracy: 0.0292
Epoch 144/1000
14/14 [==============================] - 2s 147ms/step - loss: 3.5263 - categorical_accuracy: 0.0321
Epoch 145/1000
14/14 [==============================] - 2s 153ms/step - loss: 3.5552 - categorical_accuracy: 0.0280
Epoch 146/1000
14/14 [==============================] - 2s 156ms/step - loss: 3.5418 - categorical_accuracy: 0.0274
Epoch 147/1000
14/14 [==============================] - 2s 159ms/step - loss: 3.5127 - categorical_accuracy: 0.0256
Epoch 148/1000
14/14 [==============================] - 2s 156ms/step - loss: 3.5227 - categorical_accuracy: 0.0363
Epoch 149/1000
14/14 [==============================] - 2s 156ms/step - loss: 3.5319 - categorical_accuracy: 0.0387
Epoch 150/1000
14/14 [==============================] - 2s 168ms/step - loss: 3.4813 - 

14/14 [==============================] - 2s 153ms/step - loss: 2.5470 - categorical_accuracy: 0.1631
Epoch 213/1000
14/14 [==============================] - 2s 153ms/step - loss: 2.5975 - categorical_accuracy: 0.1405
Epoch 214/1000
14/14 [==============================] - 2s 152ms/step - loss: 2.5872 - categorical_accuracy: 0.1464
Epoch 215/1000
14/14 [==============================] - 2s 168ms/step - loss: 2.5625 - categorical_accuracy: 0.1661
Epoch 216/1000
14/14 [==============================] - 2s 163ms/step - loss: 2.5602 - categorical_accuracy: 0.1631
Epoch 217/1000
14/14 [==============================] - 2s 162ms/step - loss: 2.5282 - categorical_accuracy: 0.1815
Epoch 218/1000
14/14 [==============================] - 3s 176ms/step - loss: 2.5263 - categorical_accuracy: 0.1774
Epoch 219/1000
14/14 [==============================] - 2s 159ms/step - loss: 2.5486 - categorical_accuracy: 0.1655
Epoch 220/1000
14/14 [==============================] - 2s 166ms/step - loss: 2.5268 - 

14/14 [==============================] - 2s 176ms/step - loss: 2.4332 - categorical_accuracy: 0.2167
Epoch 283/1000
14/14 [==============================] - 2s 173ms/step - loss: 2.4260 - categorical_accuracy: 0.2083
Epoch 284/1000
14/14 [==============================] - 3s 194ms/step - loss: 2.4251 - categorical_accuracy: 0.2179
Epoch 285/1000
14/14 [==============================] - 3s 210ms/step - loss: 2.4135 - categorical_accuracy: 0.2042
Epoch 286/1000
14/14 [==============================] - 3s 181ms/step - loss: 2.4089 - categorical_accuracy: 0.2024
Epoch 287/1000
14/14 [==============================] - 3s 191ms/step - loss: 2.4097 - categorical_accuracy: 0.2137
Epoch 288/1000
14/14 [==============================] - 3s 181ms/step - loss: 2.4012 - categorical_accuracy: 0.2071
Epoch 289/1000
14/14 [==============================] - 2s 158ms/step - loss: 2.4089 - categorical_accuracy: 0.2137
Epoch 290/1000
14/14 [==============================] - 2s 167ms/step - loss: 2.3783 - 

14/14 [==============================] - 2s 146ms/step - loss: 2.2014 - categorical_accuracy: 0.2726
Epoch 353/1000
14/14 [==============================] - 2s 148ms/step - loss: 2.1492 - categorical_accuracy: 0.2851
Epoch 354/1000
14/14 [==============================] - 2s 146ms/step - loss: 2.0992 - categorical_accuracy: 0.3089
Epoch 355/1000
14/14 [==============================] - 2s 150ms/step - loss: 2.0975 - categorical_accuracy: 0.2893
Epoch 356/1000
14/14 [==============================] - 2s 146ms/step - loss: 2.1295 - categorical_accuracy: 0.2869
Epoch 357/1000
14/14 [==============================] - 2s 149ms/step - loss: 2.1078 - categorical_accuracy: 0.3071
Epoch 358/1000
14/14 [==============================] - 2s 146ms/step - loss: 2.0606 - categorical_accuracy: 0.3125
Epoch 359/1000
14/14 [==============================] - 2s 146ms/step - loss: 2.0592 - categorical_accuracy: 0.3232
Epoch 360/1000
14/14 [==============================] - 2s 146ms/step - loss: 2.1088 - 

14/14 [==============================] - 2s 158ms/step - loss: 1.7629 - categorical_accuracy: 0.3923
Epoch 423/1000
14/14 [==============================] - 2s 152ms/step - loss: 1.8073 - categorical_accuracy: 0.4018
Epoch 424/1000
14/14 [==============================] - 2s 155ms/step - loss: 1.8167 - categorical_accuracy: 0.3923
Epoch 425/1000
14/14 [==============================] - 2s 152ms/step - loss: 1.8812 - categorical_accuracy: 0.3738
Epoch 426/1000
14/14 [==============================] - 2s 154ms/step - loss: 1.8024 - categorical_accuracy: 0.3923
Epoch 427/1000
14/14 [==============================] - 2s 155ms/step - loss: 1.7516 - categorical_accuracy: 0.4048
Epoch 428/1000
14/14 [==============================] - 2s 166ms/step - loss: 1.8179 - categorical_accuracy: 0.3857
Epoch 429/1000
14/14 [==============================] - 2s 168ms/step - loss: 1.7437 - categorical_accuracy: 0.4095
Epoch 430/1000
14/14 [==============================] - 2s 161ms/step - loss: 1.8600 - 

14/14 [==============================] - 2s 153ms/step - loss: 1.6516 - categorical_accuracy: 0.4464
Epoch 493/1000
14/14 [==============================] - 2s 157ms/step - loss: 1.6275 - categorical_accuracy: 0.4333
Epoch 494/1000
14/14 [==============================] - 2s 162ms/step - loss: 1.6096 - categorical_accuracy: 0.4440
Epoch 495/1000
14/14 [==============================] - 2s 152ms/step - loss: 1.5965 - categorical_accuracy: 0.4601
Epoch 496/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.5491 - categorical_accuracy: 0.4679
Epoch 497/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.5896 - categorical_accuracy: 0.4363
Epoch 498/1000
14/14 [==============================] - 2s 154ms/step - loss: 1.6370 - categorical_accuracy: 0.4333
Epoch 499/1000
14/14 [==============================] - 2s 160ms/step - loss: 1.6028 - categorical_accuracy: 0.4548
Epoch 500/1000
14/14 [==============================] - 2s 158ms/step - loss: 1.5963 - 

14/14 [==============================] - 2s 154ms/step - loss: 1.4919 - categorical_accuracy: 0.4774
Epoch 563/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.4668 - categorical_accuracy: 0.4958
Epoch 564/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.5201 - categorical_accuracy: 0.4881
Epoch 565/1000
14/14 [==============================] - 2s 155ms/step - loss: 1.4516 - categorical_accuracy: 0.4976
Epoch 566/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.5205 - categorical_accuracy: 0.4786
Epoch 567/1000
14/14 [==============================] - 2s 161ms/step - loss: 1.4717 - categorical_accuracy: 0.5006
Epoch 568/1000
14/14 [==============================] - 2s 160ms/step - loss: 1.4659 - categorical_accuracy: 0.4917
Epoch 569/1000
14/14 [==============================] - 2s 161ms/step - loss: 1.4876 - categorical_accuracy: 0.4881
Epoch 570/1000
14/14 [==============================] - 2s 154ms/step - loss: 1.4762 - 

14/14 [==============================] - 2s 157ms/step - loss: 1.2963 - categorical_accuracy: 0.5423
Epoch 633/1000
14/14 [==============================] - 2s 169ms/step - loss: 1.3057 - categorical_accuracy: 0.5405
Epoch 634/1000
14/14 [==============================] - 2s 167ms/step - loss: 1.3818 - categorical_accuracy: 0.5339
Epoch 635/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.3878 - categorical_accuracy: 0.5173
Epoch 636/1000
14/14 [==============================] - 2s 154ms/step - loss: 1.3322 - categorical_accuracy: 0.5214
Epoch 637/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.3924 - categorical_accuracy: 0.5185
Epoch 638/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.3456 - categorical_accuracy: 0.5173
Epoch 639/1000
14/14 [==============================] - 2s 152ms/step - loss: 1.3237 - categorical_accuracy: 0.5375
Epoch 640/1000
14/14 [==============================] - 2s 154ms/step - loss: 1.3932 - 

14/14 [==============================] - 2s 156ms/step - loss: 1.2135 - categorical_accuracy: 0.5690
Epoch 703/1000
14/14 [==============================] - 2s 151ms/step - loss: 1.2403 - categorical_accuracy: 0.5589
Epoch 704/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.2678 - categorical_accuracy: 0.5482
Epoch 705/1000
14/14 [==============================] - 2s 150ms/step - loss: 1.2589 - categorical_accuracy: 0.5565
Epoch 706/1000
14/14 [==============================] - 2s 150ms/step - loss: 1.2648 - categorical_accuracy: 0.5488
Epoch 707/1000
14/14 [==============================] - 2s 152ms/step - loss: 1.2084 - categorical_accuracy: 0.5625
Epoch 708/1000
14/14 [==============================] - 2s 150ms/step - loss: 1.1952 - categorical_accuracy: 0.5798
Epoch 709/1000
14/14 [==============================] - 2s 149ms/step - loss: 1.1936 - categorical_accuracy: 0.5714
Epoch 710/1000
14/14 [==============================] - 2s 151ms/step - loss: 1.2485 - 

14/14 [==============================] - 2s 151ms/step - loss: 3.5591 - categorical_accuracy: 0.0357
Epoch 773/1000
14/14 [==============================] - 2s 151ms/step - loss: 3.5644 - categorical_accuracy: 0.0452
Epoch 774/1000
14/14 [==============================] - 2s 150ms/step - loss: 3.6488 - categorical_accuracy: 0.0625
Epoch 775/1000
14/14 [==============================] - 2s 150ms/step - loss: 3.2812 - categorical_accuracy: 0.0744
Epoch 776/1000
14/14 [==============================] - 2s 151ms/step - loss: 3.2416 - categorical_accuracy: 0.0970
Epoch 777/1000
14/14 [==============================] - 2s 156ms/step - loss: 3.0954 - categorical_accuracy: 0.1000
Epoch 778/1000
14/14 [==============================] - 2s 156ms/step - loss: 3.0464 - categorical_accuracy: 0.0982
Epoch 779/1000
14/14 [==============================] - 2s 152ms/step - loss: 2.9224 - categorical_accuracy: 0.1107
Epoch 780/1000
14/14 [==============================] - 2s 151ms/step - loss: 3.0900 - 

14/14 [==============================] - 2s 157ms/step - loss: 1.9121 - categorical_accuracy: 0.3512
Epoch 843/1000
14/14 [==============================] - 2s 163ms/step - loss: 1.9580 - categorical_accuracy: 0.3351
Epoch 844/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.9432 - categorical_accuracy: 0.3458
Epoch 845/1000
14/14 [==============================] - 2s 156ms/step - loss: 1.9065 - categorical_accuracy: 0.3470
Epoch 846/1000
14/14 [==============================] - 2s 155ms/step - loss: 1.9069 - categorical_accuracy: 0.3577
Epoch 847/1000
14/14 [==============================] - 2s 153ms/step - loss: 1.9894 - categorical_accuracy: 0.3488
Epoch 848/1000
14/14 [==============================] - 2s 150ms/step - loss: 1.9361 - categorical_accuracy: 0.3464
Epoch 849/1000
14/14 [==============================] - 2s 148ms/step - loss: 1.9225 - categorical_accuracy: 0.3560
Epoch 850/1000
14/14 [==============================] - 2s 149ms/step - loss: 1.8950 - 

14/14 [==============================] - 2s 152ms/step - loss: 2.7401 - categorical_accuracy: 0.1565
Epoch 913/1000
14/14 [==============================] - 2s 151ms/step - loss: 2.6166 - categorical_accuracy: 0.1780
Epoch 914/1000
14/14 [==============================] - 2s 150ms/step - loss: 2.5840 - categorical_accuracy: 0.1857
Epoch 915/1000
14/14 [==============================] - 2s 149ms/step - loss: 2.5617 - categorical_accuracy: 0.1750
Epoch 916/1000
14/14 [==============================] - 2s 150ms/step - loss: 2.4962 - categorical_accuracy: 0.2012
Epoch 917/1000
14/14 [==============================] - 2s 148ms/step - loss: 2.3705 - categorical_accuracy: 0.2143
Epoch 918/1000
14/14 [==============================] - 2s 150ms/step - loss: 2.3974 - categorical_accuracy: 0.2351
Epoch 919/1000
14/14 [==============================] - 2s 150ms/step - loss: 4.0078 - categorical_accuracy: 0.0935
Epoch 920/1000
14/14 [==============================] - 2s 149ms/step - loss: 4.6892 - 

14/14 [==============================] - 2s 152ms/step - loss: 3.5672 - categorical_accuracy: 0.0286
Epoch 983/1000
14/14 [==============================] - 2s 150ms/step - loss: 3.5602 - categorical_accuracy: 0.0286
Epoch 984/1000
14/14 [==============================] - 2s 149ms/step - loss: 3.5592 - categorical_accuracy: 0.0286
Epoch 985/1000
14/14 [==============================] - 2s 150ms/step - loss: 3.5590 - categorical_accuracy: 0.0286
Epoch 986/1000
14/14 [==============================] - 2s 150ms/step - loss: 3.5670 - categorical_accuracy: 0.0286
Epoch 987/1000
14/14 [==============================] - 2s 150ms/step - loss: 3.5589 - categorical_accuracy: 0.0286
Epoch 988/1000
14/14 [==============================] - 2s 150ms/step - loss: 3.5587 - categorical_accuracy: 0.0286
Epoch 989/1000
14/14 [==============================] - 2s 155ms/step - loss: 3.5588 - categorical_accuracy: 0.0286
Epoch 990/1000
14/14 [==============================] - 2s 156ms/step - loss: 3.5586 - 

# 5. Save Weights

In [63]:
# Save weights to be reuse later
model.save('sign_language.h5')

# 6. Evaluation using Confusion Matrix and Accuracy

In [14]:
# Import libraries
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 

In [11]:
yhat = model.predict(X_test)

In [12]:
# Convert predictions from one-hot encoded representation to categorical label
# eg: 0, 1, 2, ... as compared to [1, 0, 0] 
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [15]:
# Returns a confusion matrix sorted by the label order
# Matrix organized as 
# [[True Negative, False Positive],
#  [False Negative, True Positive]]
multilabel_confusion_matrix(ytrue, yhat)

array([[[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[  0, 408],
        [  0,  12]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12, 

In [ ]:
# ax = sns.heatmap(multilabel_confusion_matrix(ytrue, yhat), annot=True, fmt='g')

In [16]:
# Check accuracy
accuracy_score(ytrue, yhat)

0.02857142857142857

In [60]:
# Check precision scores for each class (None, micro overall)
precision_score(ytrue, yhat, average=None)

array([0.30769231, 0.7       , 0.33333333, 0.47368421, 0.54545455,
       0.5       , 0.61538462, 0.47368421, 0.75      , 0.84615385,
       0.52631579, 0.57142857, 0.5625    , 0.8       , 0.5       ,
       0.91666667, 0.83333333, 0.66666667, 0.3       , 0.69230769,
       0.33333333, 0.25      , 0.22727273, 0.27272727, 0.75      ,
       0.8       , 0.76923077, 1.        , 0.85714286, 0.66666667,
       0.78571429, 1.        , 0.84615385, 0.875     , 0.71428571])

In [61]:
# Check recall scores for each class (None, micro overall)
recall_score(ytrue, yhat, average=None)

array([0.66666667, 0.58333333, 0.33333333, 0.75      , 0.5       ,
       0.25      , 0.66666667, 0.75      , 0.75      , 0.91666667,
       0.83333333, 0.33333333, 0.75      , 0.66666667, 0.66666667,
       0.91666667, 0.41666667, 0.33333333, 0.25      , 0.75      ,
       0.08333333, 0.16666667, 0.41666667, 0.25      , 0.75      ,
       1.        , 0.83333333, 0.41666667, 1.        , 0.33333333,
       0.91666667, 0.5       , 0.91666667, 0.58333333, 0.83333333])

In [62]:
f1_score(ytrue, yhat, average=None)

array([0.42105263, 0.63636364, 0.33333333, 0.58064516, 0.52173913,
       0.33333333, 0.64      , 0.58064516, 0.75      , 0.88      ,
       0.64516129, 0.42105263, 0.64285714, 0.72727273, 0.57142857,
       0.91666667, 0.55555556, 0.44444444, 0.27272727, 0.72      ,
       0.13333333, 0.2       , 0.29411765, 0.26086957, 0.75      ,
       0.88888889, 0.8       , 0.58823529, 0.92307692, 0.44444444,
       0.84615385, 0.66666667, 0.88      , 0.7       , 0.76923077])