# 1. Import SignLanguageModule notebook

In [1]:
import import_ipynb
import SignLanguageModule as signLangModule # notebook converted as .py file

ERROR: Invalid requirement: '#'


['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


# 2. Collect Keypoint Values for Training and Testing

In [2]:
# Call function to collect keypoints from SignLanguageModule
# signLangModule.collect_keypoints()

# 3. Preprocess Data and Create Labels and Features

In [2]:
# Import dependencies
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [3]:
import os
import numpy as np

In [4]:
# Create label map for the signs defined in SignLanguageModule
# to be used when creating training data in testing data
label_map = {label:num for num, label in enumerate(signLangModule.signs)}

In [5]:
label_map

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25,
 'hello': 26,
 'my': 27,
 'name': 28,
 'is': 29,
 'nice': 30,
 'you': 31,
 'bye': 32,
 'thank you': 33,
 'to meet': 34}

In [6]:
# Sequences for feature (x) data
# Labels for representing labels (y) data
sequences, labels = [], []
for sign in signLangModule.signs:
    for sequence in np.array(os.listdir(os.path.join(signLangModule.DATA_PATH, sign))).astype(int):
        window = []
        for frame_num in range(signLangModule.sequence_length):
            res = np.load(os.path.join(signLangModule.DATA_PATH, sign, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[sign])

In [6]:
np.array(sequences).shape #check this one for all signs

(2100, 30, 1662)

In [7]:
np.array(labels).shape #check this too

(2100,)

In [7]:
# Store sequences into numpy array to work with
X = np.array(sequences)

# Convert initial labels, encode them as one-code representation/binary flat
y = to_categorical(labels).astype(int)

# Specify test data proportion (20% of the data)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y) 

In [16]:
y_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [17]:
X_train.shape

(1680, 30, 1662)

In [18]:
# Instantiate model
model = signLangModule.createModel()

In [9]:
# Check model summary
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 30, 64)            442112    
_________________________________________________________________
lstm_1 (LSTM)                (None, 30, 128)           98816     
_________________________________________________________________
lstm_2 (LSTM)                (None, 64)                49408     
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense (Dense)                (None, 700)               45500     
_________________________________________________________________
dropout_1 (Dropout)          (None, 700)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 700)               4

In [13]:
signLangModule.signs.shape[0]

35

# 4. Train the LSTM Neural Network

In [10]:
# Train the built LSTM neural network 
model.fit(X_train, y_train, batch_size=128, epochs=1000, callbacks=[signLangModule.tb_callback])

Epoch 1/1000
14/14 [==============================] - 4s 141ms/step - loss: 4.1232 - categorical_accuracy: 0.0315
Epoch 2/1000
14/14 [==============================] - 2s 118ms/step - loss: 3.5628 - categorical_accuracy: 0.0274
Epoch 3/1000
14/14 [==============================] - 2s 121ms/step - loss: 3.5563 - categorical_accuracy: 0.0292
Epoch 4/1000
14/14 [==============================] - 2s 124ms/step - loss: 3.5556 - categorical_accuracy: 0.0333
Epoch 5/1000
14/14 [==============================] - 2s 125ms/step - loss: 3.5533 - categorical_accuracy: 0.0321
Epoch 6/1000
14/14 [==============================] - 2s 130ms/step - loss: 3.5519 - categorical_accuracy: 0.0244
Epoch 7/1000
14/14 [==============================] - 2s 134ms/step - loss: 3.5550 - categorical_accuracy: 0.0310
Epoch 8/1000
14/14 [==============================] - 2s 130ms/step - loss: 3.5547 - categorical_accuracy: 0.0262
Epoch 9/1000
14/14 [==============================] - 2s 131ms/step - loss: 3.5640 - cat

14/14 [==============================] - 2s 161ms/step - loss: 3.5555 - categorical_accuracy: 0.0298
Epoch 73/1000
14/14 [==============================] - 2s 166ms/step - loss: 3.5571 - categorical_accuracy: 0.0286
Epoch 74/1000
14/14 [==============================] - 3s 182ms/step - loss: 3.5569 - categorical_accuracy: 0.0280
Epoch 75/1000
14/14 [==============================] - 3s 190ms/step - loss: 3.5554 - categorical_accuracy: 0.0286
Epoch 76/1000
14/14 [==============================] - 2s 167ms/step - loss: 3.5561 - categorical_accuracy: 0.0286
Epoch 77/1000
14/14 [==============================] - 3s 198ms/step - loss: 3.5556 - categorical_accuracy: 0.0292
Epoch 78/1000
14/14 [==============================] - 2s 158ms/step - loss: 3.5613 - categorical_accuracy: 0.0286
Epoch 79/1000
14/14 [==============================] - 2s 162ms/step - loss: 3.5579 - categorical_accuracy: 0.0268
Epoch 80/1000
14/14 [==============================] - 3s 190ms/step - loss: 3.5592 - categori

Epoch 143/1000
14/14 [==============================] - 2s 156ms/step - loss: 3.5558 - categorical_accuracy: 0.0262
Epoch 144/1000
14/14 [==============================] - 2s 160ms/step - loss: 3.5557 - categorical_accuracy: 0.0286
Epoch 145/1000
14/14 [==============================] - 2s 156ms/step - loss: 3.5567 - categorical_accuracy: 0.0286
Epoch 146/1000
14/14 [==============================] - 2s 164ms/step - loss: 3.5570 - categorical_accuracy: 0.0286
Epoch 147/1000
14/14 [==============================] - 2s 164ms/step - loss: 3.5559 - categorical_accuracy: 0.0286
Epoch 148/1000
14/14 [==============================] - 2s 169ms/step - loss: 3.5556 - categorical_accuracy: 0.0286
Epoch 149/1000
14/14 [==============================] - 3s 231ms/step - loss: 3.5559 - categorical_accuracy: 0.0286
Epoch 150/1000
14/14 [==============================] - 3s 200ms/step - loss: 3.5553 - categorical_accuracy: 0.0286
Epoch 151/1000
14/14 [==============================] - 2s 174ms/step - 

14/14 [==============================] - 2s 161ms/step - loss: 3.5588 - categorical_accuracy: 0.0286
Epoch 214/1000
14/14 [==============================] - 2s 173ms/step - loss: 3.5558 - categorical_accuracy: 0.0286
Epoch 215/1000
14/14 [==============================] - 2s 165ms/step - loss: 3.5554 - categorical_accuracy: 0.0286
Epoch 216/1000
14/14 [==============================] - 3s 184ms/step - loss: 3.5570 - categorical_accuracy: 0.0292
Epoch 217/1000
14/14 [==============================] - 3s 179ms/step - loss: 3.5549 - categorical_accuracy: 0.0286
Epoch 218/1000
14/14 [==============================] - 2s 164ms/step - loss: 3.5552 - categorical_accuracy: 0.0286
Epoch 219/1000
14/14 [==============================] - 2s 169ms/step - loss: 3.5555 - categorical_accuracy: 0.0286
Epoch 220/1000
14/14 [==============================] - 2s 163ms/step - loss: 3.5572 - categorical_accuracy: 0.0286
Epoch 221/1000
14/14 [==============================] - 2s 154ms/step - loss: 3.5559 - 

KeyboardInterrupt: 

# 5. Save Weights

In [63]:
# Save weights to be reuse later
model.save('sign_language.h5')

# 6. Evaluation using Confusion Matrix and Accuracy

In [14]:
# Import libraries
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score, precision_score, recall_score, f1_score 

In [19]:
yhat = model.predict(X_test)

In [20]:
# Convert predictions from one-hot encoded representation to categorical label
# eg: 0, 1, 2, ... as compared to [1, 0, 0] 
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [21]:
# Returns a confusion matrix sorted by the label order
# Matrix organized as 
# [[True Negative, False Positive],
#  [False Negative, True Positive]]
multilabel_confusion_matrix(ytrue, yhat)

array([[[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[  0, 408],
        [  0,  12]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12,   0]],

       [[408,   0],
        [ 12, 

In [ ]:
# ax = sns.heatmap(multilabel_confusion_matrix(ytrue, yhat), annot=True, fmt='g')

In [22]:
# Check accuracy
accuracy_score(ytrue, yhat)

0.02857142857142857

In [60]:
# Check precision scores for each class (None, micro overall)
precision_score(ytrue, yhat, average=None)

array([0.30769231, 0.7       , 0.33333333, 0.47368421, 0.54545455,
       0.5       , 0.61538462, 0.47368421, 0.75      , 0.84615385,
       0.52631579, 0.57142857, 0.5625    , 0.8       , 0.5       ,
       0.91666667, 0.83333333, 0.66666667, 0.3       , 0.69230769,
       0.33333333, 0.25      , 0.22727273, 0.27272727, 0.75      ,
       0.8       , 0.76923077, 1.        , 0.85714286, 0.66666667,
       0.78571429, 1.        , 0.84615385, 0.875     , 0.71428571])

In [61]:
# Check recall scores for each class (None, micro overall)
recall_score(ytrue, yhat, average=None)

array([0.66666667, 0.58333333, 0.33333333, 0.75      , 0.5       ,
       0.25      , 0.66666667, 0.75      , 0.75      , 0.91666667,
       0.83333333, 0.33333333, 0.75      , 0.66666667, 0.66666667,
       0.91666667, 0.41666667, 0.33333333, 0.25      , 0.75      ,
       0.08333333, 0.16666667, 0.41666667, 0.25      , 0.75      ,
       1.        , 0.83333333, 0.41666667, 1.        , 0.33333333,
       0.91666667, 0.5       , 0.91666667, 0.58333333, 0.83333333])

In [62]:
f1_score(ytrue, yhat, average=None)

array([0.42105263, 0.63636364, 0.33333333, 0.58064516, 0.52173913,
       0.33333333, 0.64      , 0.58064516, 0.75      , 0.88      ,
       0.64516129, 0.42105263, 0.64285714, 0.72727273, 0.57142857,
       0.91666667, 0.55555556, 0.44444444, 0.27272727, 0.72      ,
       0.13333333, 0.2       , 0.29411765, 0.26086957, 0.75      ,
       0.88888889, 0.8       , 0.58823529, 0.92307692, 0.44444444,
       0.84615385, 0.66666667, 0.88      , 0.7       , 0.76923077])